
N=500;
Lfft=1024;
freq=[0:Lfft-1]/Lfft;

%complex process generated by the all pole filtering of a white noise
a=[1,-2.4788,3.0905,-2.0646,0.6856];
sw=[1;0*1i]; 
Pw=sw'*sw;
w=randn(N,2)*sw;
x=filter(1,a,w);

%K and the window type can be modified:
K=50;
sest=covtodsp(x,K,'b',Lfft);
sestlog=10*log10(sest);
sth=10*log10(Pw*abs(1./fft(a,Lfft)).^2);
direct_spectrum = 10*log10(abs(fft(x,Lfft)).^2/Lfft);
plot(freq,sth,freq,sestlog,'r',freq,direct_spectrum); grid
legend('theory','estimation','direct spectrum');
set(gca,'xlim',[0,1/2]); %if x is real







